# Generated by Django 5.2.17 on 2026-09-11 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_name",
                    models.CharField(max_length=255, verbose_name="Xomashyo nomi"),
                ),
            ],
            options={
                "verbose_name": "Xomashyo",
                "verbose_name_plural": "Xomashyolar",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Mahsulot nomi"),
                ),
                (
                    "product_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mahsulot kodi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahsulot",
                "verbose_name_plural": "Mahsulotlar",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remainder", models.FloatField(verbose_name="Qoldiq miqdori")),
                ("price", models.FloatField(verbose_name="Kelgan narxi")),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouses",
                        to="warehouse.material",
                        verbose_name="Xomashyo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ombor partiyasi",
                "verbose_name_plural": "Ombor partiyalari",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProductMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField(verbose_name="Kerakli miqdor")),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_materials",
                        to="warehouse.material",
                        verbose_name="Xomashyo",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_materials",
                        to="warehouse.product",
                        verbose_name="Mahsulot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahsulot xomashyosi",
                "verbose_name_plural": "Mahsulot xomashyolari",
                "unique_together": {("product", "material")},
            },
        ),
    ]
